Feature/28 22
zapaza/teamwork_02 pull request #11
Opened 2023-07-26 21:54 UTC by SatanLittleHelper

### Какую задачу решаем

add validator
### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-07-27 07:26 UTC, TolkachevPeter commented on packages/client/src/components/ui/input/input.tsx
> +        // value={value}
вот ты тоже убрал это)

2023-07-29 07:25 UTC, Olegas requested changes
Добрый день.
Есть замечания по коду - написал подробно в комментариях.
Общие рекомендации:
- не оставлять закомментированные и неиспользуемые участки кода в проекте
- не забывать удалять отладочный вывод (console.log)
- постараться не подламывать типы через as any

2023-07-29 07:25 UTC, Olegas commented on packages/client/src/core/validator/index.ts
> +    .matches(/.+@.+\..+/, 'Invalid email'),
Строкой выше - .email() - эта проверка уже проверит что введенное значение - email

2023-07-29 07:25 UTC, Olegas commented on packages/client/src/core/validator/index.ts
> +        console.log(value)
В этом PR очень много console.log. Не надо оставлять в проекте отладочный вывод.

2023-07-29 07:25 UTC, Olegas commented on packages/client/src/core/validator/index.ts
> +      message: "Can't contain space and special symbols",
Совет: выберите один стиль написания строк (в одинарных или в двойных кавычках) и придерживайтесь его во всем проекте. Для контроля можно использовать ESLint и/или Prettier

2023-07-29 07:25 UTC, Olegas commented on packages/client/src/components/ui/input/input.tsx
> +  const [value, setValue] = useState('')
Если несколькими строками ниже убрано использование этого стейта - он тут остался не нужным. Не надо оставлять неиспользуемый код. Также не надо оставлять закомментированные куски. Или удаляем, или надо написать комментарий - зачем этот код оставлен.

2023-07-29 07:25 UTC, Olegas commented on packages/client/src/pages/login/login-page.tsx
> +        fetchLogin(data) as any
Зачем здесь as any? Какую ошибку этим заглушаем? Redux вполне хорошо типизуется и можно обойтись без подломов типизации

2023-07-29 19:20 UTC, Olegas approved these changes
Работа принята

2023-07-30 10:39 UTC, merged