Add profile page (28-26)
zapaza/teamwork_02 pull request #13
Opened 2023-07-30 13:16 UTC by Kustov-Ilya

### Создана страница пользователя
Добавлено обновление данных, пароля, аватара
Все обновления работают на модальных окнах с Form компонентом внутри

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-07-31 10:05 UTC, SatanLittleHelper commented on packages/client/src/core/api/apiProfile.ts
> +const uri = 'https://ya-praktikum.tech/api/v2'
опечатка? url должно быть? Или я что-то не знаю?

2023-07-31 10:08 UTC, Kustov-Ilya commented on packages/client/src/core/api/apiProfile.ts
> +const uri = 'https://ya-praktikum.tech/api/v2'
URI – имя и адрес ресурса в сети, включает в себя URL и URN
URL – адрес ресурса в сети, определяет местонахождение и способ обращения к нему
URN – имя ресурса в сети, определяет только название ресурса, но не говорит как к нему подключиться

примеры:

URI – https://wiki.merionet.ru/images/vse-chto-vam-nuzhno-znat-pro-devops/1.png
URL - https://wiki.merionet.ru/
URN - images/vse-chto-vam-nuzhno-znat-pro-devops/1.png

2023-07-31 10:14 UTC, SatanLittleHelper commented on packages/client/src/core/api/apiProfile.ts
> +const uri = 'https://ya-praktikum.tech/api/v2'
Понял, спасибо.

2023-07-31 10:20 UTC, SatanLittleHelper commented
Я не увидел валидации у тебя. Я либо не разобрался до конца со схемами валидации либо хз. Я писал схему валидации для signup и если я ее оставлял для signin то валидатор не пропускал, на сколько я понял из за того, что в данных не хватало обязательных полей, которые были указаны в схеме. Предполагал, что для каждого случая, нужно использовать свою схему валидации. Думаю там можно как то унифицировать эти схемы, но я пока не разбирался как. Тебе нужна схема валидации и ее пропсом надо в форму передать

2023-07-31 11:22 UTC, SatanLittleHelper commented on packages/client/src/core/validator/index.ts
> +    .test('notNumbers', "Can't contain only numbers", value => {
Надо оставить оиднарные кавычки, что бы был единый стиль кавычек

2023-07-31 11:36 UTC, Kustov-Ilya commented on packages/client/src/core/validator/index.ts
> +    .test('notNumbers', "Can't contain only numbers", value => {
Done

2023-07-31 11:36 UTC, SatanLittleHelper approved these changes

2023-07-31 16:47 UTC, Sammily approved these changes

2023-08-01 06:58 UTC, TolkachevPeter commented on packages/client/src/core/api/apiProfile.ts
> +const uri = 'https://ya-praktikum.tech/api/v2'
о, не знал, спасибо)

2023-08-01 07:05 UTC, TolkachevPeter commented on packages/client/src/pages/profile/profile-page.tsx
> +          <ProfileField key={index} label={field.label} value={field.value} />
А не хочешь написать так:
          field.value && <ProfileField key={index} label={field.label} value={field.value} />

Чтобы не показывать пустые поля, раз они не приходят?
P.S. Это вопрос, а не рекомендация.

2023-08-01 07:06 UTC, TolkachevPeter commented on packages/client/src/pages/profile/profile-page.tsx
> +  const onSubmit = async (data: unknown) => {
круто

2023-08-01 07:07 UTC, TolkachevPeter commented on packages/client/src/pages/profile/profile-page.tsx
> +    </main>
Может надо со слоя page все это вынести? Слишком много логики для компонента page?

2023-08-01 07:11 UTC, TolkachevPeter commented on packages/client/src/hooks/useModal.tsx
> +export default function useModal() {
а, это в реакте так хук целый вынес? здорово, очень хорошее решение

2023-08-01 07:13 UTC, TolkachevPeter commented on packages/client/src/core/api/apiProfile.ts
> +const uri = 'https://ya-praktikum.tech/api/v2'
только у нас есть в apiAuth уже

`const url = `https://ya-praktikum.tech/api/v2`
`

и, таким образом, мы тут явно нарушаем принцип DRY.
Надо вынести uri в одно место, может быть рядом создать папку config?

2023-08-01 07:13 UTC, Kustov-Ilya commented on packages/client/src/pages/profile/profile-page.tsx
> +          <ProfileField key={index} label={field.label} value={field.value} />
не уверен, что стоит, думал об этом. Возможны прыгающие поля, особенно из-за того, что мейл и телефон обязательны для обновления атрибутов персоны, при обновлении возвращаются, а при запросе на поля пользователя не возвращаются. Таким образом, после обновления, будет прыгать

2023-08-01 07:18 UTC, TolkachevPeter commented on packages/client/src/pages/signup/signup-page.tsx
> +    console.log(data as LoginData)
надо убрать log

2023-08-01 07:18 UTC, TolkachevPeter commented on packages/client/src/store/auth/authSlice.ts
> +      return thunkAPI.rejectWithValue({ error: (error as any)?.message })
а давай тут везде as any заменим?

`      
return thunkAPI.rejectWithValue({ error: (error as Error | null)?.message })
`

2023-08-01 07:19 UTC, TolkachevPeter commented on packages/client/src/store/auth/authSlice.ts
> +      .addCase(
А так и должно все это выглядеть? Меня лично смущает addCase? Надо вчитывать в то, что тут происходит.

2023-08-01 07:20 UTC, TolkachevPeter commented on packages/client/src/components/modal/modal.tsx
> +import React, { ReactNode } from 'react'
круто

2023-08-01 07:20 UTC, Kustov-Ilya commented on packages/client/src/pages/profile/profile-page.tsx
> +    </main>
Ну, создание модалки и формы внутри я вынес, насколько возможно) Если модалку выносить на уровень с роутом, то нужно будет логику менять) Если понадобится - заведем задачу) Пока что у нас модалки только тут

2023-08-01 07:21 UTC, TolkachevPeter commented on packages/client/src/core/api/apiProfile.ts
> +import { AuthState } from '../../types/auth'
Может быть перейдем тут на kebab-case в названии файлов?

2023-08-01 07:23 UTC, Kustov-Ilya commented on packages/client/src/pages/login/login-page.tsx
> +      type="json"
Для того, чтобы сигнализировать, какой формат формы нужен. Для загрузки аватара требуется formData, для обновления атрибутов персоны требуется json

2023-08-01 07:23 UTC, TolkachevPeter commented on packages/client/src/core/api/apiAuth.ts
> +import ApiClient from './apiClient'
это же ошибка, нет? Файл называется именно ApiClient и там лежит class?

2023-08-01 07:24 UTC, TolkachevPeter commented on packages/client/src/core/api/ApiClient.ts
> +export const API_ENDPOINT = 'https://ya-praktikum.tech/api/v2'
снова uri повторяется

2023-08-01 07:24 UTC, Kustov-Ilya commented on packages/client/src/hooks/useModal.tsx
> +export default function useModal() {
спасибо) Его можно будет при необходимости нагрузить еще чем-нибудь) Пока что минимальный тоггл)

2023-08-01 07:26 UTC, TolkachevPeter commented on packages/client/src/pages/profile/profile-page.tsx
> +import { RESOURCES_URL } from '../../core/api/apiClient'
у меня лично тут ошибка при этом импорте:

```
File name '/Users/p.i.t.e.p/yandex/teamwork_02/packages/client/src/core/api/apiClient.ts' differs from already included file name '/Users/p.i.t.e.p/yandex/teamwork_02/packages/client/src/core/api/ApiClient.ts' only in casing.
  The file is in the program because:
    Imported via './ApiClient' from file '/Users/p.i.t.e.p/yandex/teamwork_02/packages/client/src/core/api/ApiAuth.ts'
    Imported via './ApiClient' from file '/Users/p.i.t.e.p/yandex/teamwork_02/packages/client/src/core/api/apiProfile.ts'
    Imported via '../../core/api/apiClient' from file '/Users/p.i.t.e.p/yandex/teamwork_02/packages/client/src/pages/profile/profile-page.tsx'
    Matched by include pattern 'src' in '/Users/p.i.t.e.p/yandex/teamwork_02/packages/client/tsconfig.json'ts(1149)
ApiAuth.ts(2, 23): File is included via import here.
apiProfile.ts(2, 23): File is included via import here.
tsconfig.json(19, 15): File is matched by include pattern specified here.
```

2023-08-01 07:26 UTC, Kustov-Ilya commented on packages/client/src/store/auth/authSlice.ts
> +      .addCase(
Ну через addCase мы добавляем обработчики для каждого запроса) Затем, когда начнет разрастаться, нужно будет раснести логику) Пока что у нас один slice, в котором хранится инфа по персоне

2023-08-01 07:27 UTC, TolkachevPeter commented on packages/client/src/pages/profile/profile-page.tsx
> +import { RESOURCES_URL } from '../../core/api/apiClient'
class и должен импортироваться с большой буквы, разве нет?

2023-08-01 07:48 UTC, Kustov-Ilya commented on packages/client/src/pages/signup/signup-page.tsx
> +    console.log(data as LoginData)
готово

2023-08-01 07:49 UTC, Kustov-Ilya commented on packages/client/src/store/auth/authSlice.ts
> +      return thunkAPI.rejectWithValue({ error: (error as any)?.message })
готово

2023-08-01 07:50 UTC, Kustov-Ilya commented on packages/client/src/core/api/apiProfile.ts
> +import { AuthState } from '../../types/auth'
готово, только конкретно в этом примере название интерфейса) Но я заменил все файлы на кебаб)

2023-08-01 07:51 UTC, Kustov-Ilya commented on packages/client/src/core/api/apiAuth.ts
> +import ApiClient from './apiClient'
Исправлено

2023-08-01 07:51 UTC, Kustov-Ilya commented on packages/client/src/pages/profile/profile-page.tsx
> +import { RESOURCES_URL } from '../../core/api/apiClient'
исправлено

2023-08-01 07:58 UTC, Kustov-Ilya commented on packages/client/src/core/api/apiProfile.ts
> +const uri = 'https://ya-praktikum.tech/api/v2'
Оставил пока что в api-client
`export const API_ENDPOINT = 'https://ya-praktikum.tech/api/v2'`
и его везде импортировал. Потом можем вынести)

2023-08-01 08:10 UTC, TolkachevPeter approved these changes

2023-08-01 08:11 UTC, TolkachevPeter commented on packages/client/src/store/auth/auth-slice.ts
> +      return thunkAPI.rejectWithValue({ error: (error as Error | null)?.message })
да, так лучше

2023-08-01 15:40 UTC, Olegas requested changes
Добрый день.
В целом - хорошо. Но на мой взгляд (да и коллеги по команде с этим согласны, были замечания на эту тему) компонент ProfilePage очень перегружен. Я бы посоветовал разбить его на несколько
Есть еще пара мелких замечаний по коду - написал их в комментариях

2023-08-01 15:40 UTC, Olegas commented on packages/client/src/components/modal/modal.tsx
> +    <>
Вот этот Fragment - явно лишний. Если не isOpen - просто верните null из рендера

2023-08-01 15:40 UTC, Olegas commented on packages/client/src/core/api/api-profile.ts
> +export type UpdateProfileReq = Record<typeof UpdateProfileType[number], string>
Какой-то очень сложный тип. А почему нельзя описать явно тип у которого перечислить поля и их значения? Зачем делать массив и через typeof UpdateProfileType[number] дальше все крутить?

2023-08-01 15:40 UTC, Olegas commented on packages/client/src/hooks/use-modal.tsx
> +  const [isOpen, setisOpen] = useState(false)
Сеттер должен называться setIsOpen

2023-08-01 15:40 UTC, Olegas commented on packages/client/src/pages/profile/profile-page.tsx
> +        {getModalForm()}
Вот эти функции - getModalForm, getProfileFields - я бы их на useMemo заменил, что бы они на каждый рендер не перестраиваллись

2023-08-01 15:40 UTC, Olegas commented on packages/client/src/pages/profile/profile-page.tsx
> +    </main>
Соглашусь, что тут прямо как-то очень много логики в одном компоненте. Я бы как-то его разбил, на несколько компонентов. Пусть бы Profile давал функционал переключения того что мы видим и вставлял нужный компонент, а там уже внутри была бы нужная форма в каждом из них.

2023-08-01 19:09 UTC, Kustov-Ilya commented on packages/client/src/components/modal/modal.tsx
> +    <>
done

2023-08-01 19:13 UTC, Kustov-Ilya commented on packages/client/src/core/api/api-profile.ts
> +export type UpdateProfileReq = Record<typeof UpdateProfileType[number], string>
Легаси из проекта первого модуля. Использовал константы для определения полей. Исправил

2023-08-01 19:15 UTC, Kustov-Ilya commented on packages/client/src/hooks/use-modal.tsx
> +  const [isOpen, setisOpen] = useState(false)
done

2023-08-01 19:19 UTC, Kustov-Ilya commented on packages/client/src/pages/profile/profile-page.tsx
> +        {getModalForm()}
done

2023-08-01 21:20 UTC, Kustov-Ilya commented on packages/client/src/pages/profile/profile-page.tsx
> +    </main>
исправил. Вынес модалки в отдельные компоненты

2023-08-02 05:56 UTC, Olegas approved these changes
Теперь все супер, молодец! Работа принята

2023-08-02 07:04 UTC, merged