Feature/28 43
zapaza/teamwork_02 pull request #21
Opened 2023-08-08 22:09 UTC by SatanLittleHelper

### Какую задачу решаем
add handling and styling fullscreen game element

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-08-09 08:17 UTC, Kustov-Ilya reviewed
Выглядит круто, и работает хорошо) Набросал несколько идей, как можно улучшить)

2023-08-09 08:17 UTC, Kustov-Ilya commented on packages/client/src/components/game/game.tsx
> +      <div className={props.isFullscreen ? 'game-fullscreen' : 'game'}>
думаю, это можно вынести как функцию вида 
``` const modifyClassFS = (className,isFS) => `${className}${isFS?'_fullscreen':''}` ```
и использовать во всех местах. Можно вынести за пределы компоненты, либо обернуть в useCallback чтобы не происходила ререндера

2023-08-09 08:17 UTC, Kustov-Ilya commented on packages/client/src/pages/game/game-page.tsx
> +  }, [])
Это возможно вынести в хук, чтобы облегчить логику на странице?

2023-08-09 08:44 UTC, Sammily approved these changes

2023-08-09 22:03 UTC, SatanLittleHelper commented on packages/client/src/components/game/game.tsx
> +      <div className={props.isFullscreen ? 'game-fullscreen' : 'game'}>
Отличная идея, спасибо

2023-08-09 22:23 UTC, Kustov-Ilya approved these changes
Все супер)

2023-08-09 22:28 UTC, Kustov-Ilya commented
Только можешь еще хук вынести в диру хуков? Думаю, тоггл можно оставить в утилзах.

2023-08-10 13:36 UTC, Olegas requested changes
Добрый день.
Написал комментарии к коду. Есть ошибки, нужно доработать.

2023-08-10 13:36 UTC, Olegas commented on packages/client/src/pages/game/game-page.tsx
> +  })
Этот эффект будет вызываться на каждый рендер. Каждый раз будет навешиваться обработчик. А старый удаляться не будет.

2023-08-10 15:04 UTC, SatanLittleHelper commented on packages/client/src/utils/Fullscreen.ts
> +    )
Без такой конструкции, почему-то промис всегда в статусе pending и выдает ошибку в консол, при этом все работает.  Я 2 дня гуглил и пытался найти более адекватное решение, но не смог

2023-08-11 14:10 UTC, SatanLittleHelper commented on packages/client/src/utils/Fullscreen.ts
> +    )
В общем я разобрался с чем проблема. Ошибка из за того, что по даблклику - это неявный вызов фулскрина, что бы решить этот вопрос, нужно делать вызов фулскрина по кнопке, а мне так не нравится. Это проблема все таки или можно оставить так, как есть сейчас?

2023-08-12 13:33 UTC, Olegas commented on packages/client/src/utils/Fullscreen.ts
> +    )
Ну то что написано в коде выглядит очень странно и точно не помогает решить проблему, о которой сообщает браузер. Т.е. помогает но не очевидно. Если API выбрасывает ошибку, ты с ней не согласен (ок, но я бы задумался, может это делается не просто так или может в будущем пропадет поддержка такой возможности), то тогда обработай ее явно - добавь .catch() можно с пустой какой-то функцией, и напиши комментарий - зачем это сделано (обрабатывается такая-то ошибка, осознанно ее подавляем что бы она не лезла в консоль).
А .then(() => 1, () => 2) выглядит как какие-то опыты, которые забыли из кода убрать при отдаче на ревью.

2023-08-12 21:48 UTC, SatanLittleHelper commented on packages/client/src/utils/Fullscreen.ts
> +    )
Самое странное, что через .catch она не отлавливается. Я в итоге переделал на фулскрин по кнопке, что бы избавиться от этой ошибки, но так же оставил возможность использовать старую логику, если вдруг мы захотим

2023-08-13 12:09 UTC, SatanLittleHelper commented
Конфликты решил, но не пушу тк нельзя пушить, послет ого как отправил на ревью. Когда отправлял небыло конфликта

2023-08-13 16:04 UTC, Olegas requested changes
Остались замечания по коду, нужно доработать. Написал комментарии.

2023-08-13 16:04 UTC, Olegas commented on packages/client/src/utils/Fullscreen.ts
> +    document.webkitExitFullscreen().then()
Не надо оставлять пустые then(). Я утверждаю что это не требуется для успешной и корректной работы full screen api

2023-08-13 16:04 UTC, Olegas commented on packages/client/src/utils/Fullscreen.ts
> +  removeFullscreenListener: true | false = false
А когда используются эти два параметра - type и removeFullscreenListener? Не нашел примеров использования. Они точно нужны?

2023-08-13 16:04 UTC, Olegas commented on packages/client/src/utils/Fullscreen.ts
> +    if (!removeFullscreenListener) {
Скорее всего отписка тут не работает. Потому что каждый раз создается новая функция handler

2023-08-13 16:11 UTC, SatanLittleHelper commented on packages/client/src/utils/Fullscreen.ts
> +    document.webkitExitFullscreen().then()
Согласен, но тогда висит ворнинг, что промис не обработан.

2023-08-13 16:12 UTC, SatanLittleHelper commented on packages/client/src/utils/Fullscreen.ts
> +  removeFullscreenListener: true | false = false
Сейчас не используются. В дальнейших иттерациях, после обсуждения с командой, если решим, что нам такой функционал не нужен, мы его удалим

2023-08-13 16:37 UTC, SatanLittleHelper commented on packages/client/src/utils/Fullscreen.ts
> +    if (!removeFullscreenListener) {
Я на 99% уверен, что она работает, тк проверял, перед тем как делать пр и переделать все на использование кнопки

2023-08-13 16:41 UTC, SatanLittleHelper commented on packages/client/src/utils/Fullscreen.ts
> +    document.webkitExitFullscreen().then()
Добавил обработку ошибок

2023-08-13 16:41 UTC, SatanLittleHelper commented on packages/client/src/utils/Fullscreen.ts
> +  removeFullscreenListener: true | false = false
удалил

2023-08-13 16:42 UTC, SatanLittleHelper commented on packages/client/src/utils/Fullscreen.ts
> +    if (!removeFullscreenListener) {
удалил, тк код не используется

2023-08-14 07:41 UTC, Olegas approved these changes
Работа принята

2023-08-14 09:13 UTC, merged