feat/ Добавить Service Workers
zapaza/teamwork_02 pull request #27
Opened 2023-08-13 07:32 UTC by TolkachevPeter

### Какую задачу решаем
Приложение должно попадать в кеш при первой загрузке и после этого загружаться без интернета — не только элементы входа и пользовательские настройки, но и сама игра. Допускается использование плагинов для создания конфигурации воркера, но сам функционал требуется написать самостоятельно в соответствии с материалами из уроков.
Работает только в production режиме, так и задумано.

Проверить можно так:
npm run build
npm run preview 
перейти в оффлайн режим
### Скриншоты/видяшка (если есть)
<img width="1742" alt="Screenshot 2023-08-13 at 10 30 32" src="https://github.com/zapaza/teamwork_02/assets/52109421/99589d2a-936d-491f-81b7-87068942ab49">

### TBD (если есть)

2023-08-13 07:40 UTC, TolkachevPeter commented on packages/client/src/components/ui/form/form.tsx
> +        //@ts-ignore
добавил к чужой задаче, чтобы быстрее сделать npm run build (не входило в мою задачу)

2023-08-13 07:40 UTC, TolkachevPeter commented on packages/client/src/core/game/timer.ts
> +      //@ts-ignore
добавил к чужой задаче, чтобы быстрее сделать npm run build (не входило в мою задачу)

2023-08-13 07:41 UTC, TolkachevPeter commented on packages/client/src/pages/error/error-page.tsx
> +  const is404 = (error as any)?.status === 404
добавил к чужой задаче, чтобы быстрее сделать npm run build (не входило в мою задачу), вообще тут по делу ругается ts как мне кажется.

2023-08-13 11:37 UTC, zapaza commented on packages/client/src/service-worker.ts
> +  ;(event as FetchEvent).respondWith(
почему ; в начале?

2023-08-13 11:56 UTC, SatanLittleHelper commented on packages/client/src/service-worker.ts
> +  ;(event as FetchEvent).respondWith(
Тот же вопрос

2023-08-13 17:01 UTC, TolkachevPeter commented on packages/client/src/service-worker.ts
> +  ;(event as FetchEvent).respondWith(
ой, спасибо, ошибся

2023-08-13 17:03 UTC, TolkachevPeter commented on packages/client/src/service-worker.ts
> +  ;(event as FetchEvent).respondWith(
а так eslint делает, не знаю почему

2023-08-13 17:13 UTC, TolkachevPeter commented on packages/client/src/service-worker.ts
> +  (event as InstallEvent).waitUntil(
убрал `;`

2023-08-13 17:14 UTC, SatanLittleHelper approved these changes

2023-08-13 21:19 UTC, IvanPeleshok commented on packages/client/offline.html
> +        body {
Поехали отступы

2023-08-13 21:20 UTC, IvanPeleshok commented on packages/client/src/components/ui/form/form.tsx
> +        //@ts-ignore
Предлагаю разобраться с этой ошибкой в рамках этой задачки
Уверен, что решение достаточно простое

2023-08-13 21:20 UTC, IvanPeleshok commented on packages/client/src/core/game/timer.ts
> +      //@ts-ignore
Предлагаю разобраться с этой ошибкой в рамках этой задачки
Уверен, что решение достаточно простое

2023-08-13 21:21 UTC, IvanPeleshok commented on packages/client/src/pages/error/error-page.tsx
> +  const is404 = (error as any)?.status === 404
Предлагаю разобраться с этой ошибкой в рамках этой задачки
Уверен, что решение достаточно простое

2023-08-13 21:21 UTC, IvanPeleshok commented on packages/client/src/service-worker.ts
> +    caches.match((event as FetchEvent).request).then(cachedResponse => {
Предлагаю переписать на async / await + try / catch
Пишем плоский код, который проще читать

2023-08-13 21:22 UTC, IvanPeleshok commented on packages/client/src/service-worker.ts
> +      return fetch((event as FetchEvent).request).then(response => {
Аналогично

2023-08-13 21:22 UTC, IvanPeleshok commented on packages/client/src/service-worker.ts
> +    caches.keys().then(cacheNames => {
async / await + try / catch

2023-08-13 21:22 UTC, IvanPeleshok requested changes
Хорошая работа, но есть небольшие замечания

2023-08-14 12:24 UTC, TolkachevPeter commented on packages/client/src/service-worker.ts
> +    caches.keys().then(cacheNames => {
переписал

2023-08-14 12:26 UTC, TolkachevPeter commented on packages/client/src/core/game/timer.ts
> +      //@ts-ignore
но это не моя задача, коллеги потом ругаться будут, так что не полезу, все работает и ок.

Тем более это движок игры.

2023-08-14 18:55 UTC, IvanPeleshok commented on packages/client/src/core/game/timer.ts
> +      //@ts-ignore
@TolkachevPeter, ругаться они точно не стали бы :), только респект

Обязательно запишите моменты с игнором в тех.долг

2023-08-14 18:55 UTC, IvanPeleshok approved these changes

2023-08-15 06:14 UTC, merged