Feature/28 35
zapaza/teamwork_02 pull request #28
Opened 2023-08-13 19:21 UTC by SatanLittleHelper

### Какую задачу решаем
add states for game page

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-08-13 19:49 UTC, zapaza requested changes

2023-08-13 19:49 UTC, zapaza commented on packages/client/src/components/game/startGameState/startGameState.tsx
> +          <Button name="play" children="Играть" onClick={props.callback} />
давай играть заменим на инглиш, а то у нас пол приложения на русском, пол на иглише

2023-08-13 19:49 UTC, zapaza commented on packages/client/src/core/game/game.ts
> +      if (variables.isGamePaused) return
давай вынесем на верх и добавил {}

2023-08-13 19:49 UTC, zapaza commented on packages/client/src/core/game/graphics.ts
> +    if (variables.isGamePaused) return
и тут {}

2023-08-13 19:49 UTC, zapaza commented on packages/client/src/core/game/graphics.ts
> +    if (variables.isGamePaused) return
и тут {}

2023-08-13 19:49 UTC, zapaza commented on packages/client/src/pages/game/game-page.tsx
> +  }, [state])
надо бы удалить

2023-08-13 19:49 UTC, zapaza commented on packages/client/src/store/game/gameSlice.ts
> +        isLoading: false,
может эти методы по другому записать?

к примеру так 
```
return Object.assign({}, initialState)

//пример для play
return  Object.assign({}, initialState,  { isStart: false, isPlay: true, })
```

2023-08-13 19:52 UTC, zapaza commented on packages/client/src/store/game/gameSlice.ts
> +        isLoading: false,
если я правильно понял то тут же нужно новый объект возвразать

2023-08-13 20:01 UTC, SatanLittleHelper commented on packages/client/src/store/game/gameSlice.ts
> +        isLoading: false,
Я на самом деле смотрел как в auth сделано и делал так же. Наверно можно и так и так, но кажется мой вариант более читаемый, а код это сильно не сократит

2023-08-13 20:04 UTC, zapaza commented on packages/client/src/store/game/gameSlice.ts
> +        isLoading: false,
Ну вот я не сразу понял в чем отличия, пришлось вглядываться где меняются true false

В моем варианте сразу видно, что на что меняется

2023-08-13 20:21 UTC, SatanLittleHelper commented on packages/client/src/store/game/gameSlice.ts
> +        isLoading: false,
В твоем варианте, в теории,  мы можем случайно получить 2 значения тру, чего бы не хотелось

2023-08-13 20:24 UTC, zapaza approved these changes

2023-08-13 20:26 UTC, SatanLittleHelper commented on packages/client/src/store/game/gameSlice.ts
> +        isLoading: false,
Предлагаю, пусть еще @TolkachevPeter на эту тему выскажется. Он с редаксом разбирался, может он лучше знает как правильнее

2023-08-14 14:34 UTC, TolkachevPeter commented on packages/client/src/store/game/gameSlice.ts
> +        isLoading: false,
а зачем нам тут redux вообще? Неужели состояние игры нужно использовать во многих компонентах?

2023-08-14 14:45 UTC, TolkachevPeter commented on packages/client/src/store/game/gameSlice.ts
> +        isLoading: false,
так легче будет работать

2023-08-14 14:47 UTC, TolkachevPeter commented on packages/client/src/core/game/gameHooks.ts
> +    store.dispatch(gameSlice.actions.play())
store.dispatch(gameSlice.actions.setStatus('play'))

2023-08-14 14:47 UTC, TolkachevPeter commented on packages/client/src/core/game/eventListeners.ts
> +            store.dispatch(gameSlice.actions.pause())
store.dispatch(gameSlice.actions.setStatus('pause'))

2023-08-14 14:49 UTC, TolkachevPeter commented on packages/client/src/core/game/eventListeners.ts
> +            store.dispatch(gameSlice.actions.play())
ну и так далее, мне кажется так проще будет

2023-08-14 15:02 UTC, SatanLittleHelper commented on packages/client/src/store/game/gameSlice.ts
> +        isLoading: false,
Редакс в целом наверно не очень нужен, но я хотел его потыкать + сохраняя глобально состояние, мы возвращаемся к тому-же состоянию игры при переходе по другим роутам. Ну и я еще не придумал как по другому связать канвас и компоненты. Вечером детальнее гляну предложение твое

2023-08-14 15:05 UTC, TolkachevPeter commented on packages/client/src/store/game/gameSlice.ts
> +        isLoading: false,
тебе в сущности не нужен этот объект:
```
      return {
        isStart: false,
        isPlay: false,
        isEnd: false,
        isPause: false,
        isLoading: true,
      }
```

Просто переключай состояние, можешь через enum сделать.

```
import { createSlice } from '@reduxjs/toolkit';
import { GameState } from '../../types/game';

export enum GameStatus {
  START = 'start',
  PLAY = 'play',
  END = 'end',
  PAUSE = 'pause',
  LOADING = 'loading',
}

const initialState: GameState = {
  status: GameStatus.START,
};

export const gameSlice = createSlice({
  name: 'game',
  initialState,
  reducers: {
    start: (state) => {
      state.status = GameStatus.START;
    },
    play: (state) => {
      state.status = GameStatus.PLAY;
    },
    end: (state) => {
      state.status = GameStatus.END;
    },
    pause: (state) => {
      state.status = GameStatus.PAUSE;
    },
    loading: (state) => {
      state.status = GameStatus.LOADING;
    },
  },
});

export default gameSlice.reducer;

```

2023-08-14 22:29 UTC, SatanLittleHelper commented on packages/client/src/core/game/eventListeners.ts
> +            store.dispatch(gameSlice.actions.play())
Переделал. Чекни еще разик и я смерджу?

2023-08-15 11:39 UTC, TolkachevPeter commented on packages/client/src/core/game/eventListeners.ts
> -          AudioManager.resumeAudio(assets.audioPlayer)
а зачем тут audio подрезал?

2023-08-15 11:40 UTC, TolkachevPeter commented on packages/client/src/store/game/gameSlice.ts
> +})
выглядит хорошо

2023-08-15 11:40 UTC, TolkachevPeter commented on packages/client/src/store/game/gameStatus.ts
> +  LOADING = 'loading',
гуд

2023-08-15 11:48 UTC, TolkachevPeter approved these changes

2023-08-15 11:49 UTC, SatanLittleHelper commented on packages/client/src/core/game/eventListeners.ts
> -          AudioManager.resumeAudio(assets.audioPlayer)
хз, пойду верну. Видимо случайно

2023-08-15 11:53 UTC, SatanLittleHelper commented on packages/client/src/core/game/eventListeners.ts
> -          AudioManager.resumeAudio(assets.audioPlayer)
Ваще странная фигня, я не удалял это. Но и из дева по идее такое подмержить не мог

2023-08-15 11:56 UTC, merged