Feature/28 62
zapaza/teamwork_02 pull request #37
Opened 2023-08-29 18:14 UTC by Sammily

**Ссылка на задачу в Linear:**

[Добавить API для лидерборда](https://linear.app/28-mf-teamwork-02/issue/28-62/dobavit-api-dlya-liderborda)

- после окончания игры результат отправляется в бэкенд
- результаты лидеров отображаются на странице лидерборда

2023-08-29 18:32 UTC, SatanLittleHelper commented on packages/client/src/pages/leaderboard/leaderboardPage.tsx
> +				<h5 className="leaderboard__header text-xl-font-bold">Список Лидеров</h5>
А такие большие отступы нужны?

2023-08-29 18:46 UTC, Sammily commented on packages/client/src/pages/leaderboard/leaderboardPage.tsx
> +				<h5 className="leaderboard__header text-xl-font-bold">Список Лидеров</h5>
в vscode вроде всё норм, обычные отступы

2023-08-29 18:49 UTC, SatanLittleHelper commented
Пусть еще кто нибудь глянет, я ничего не заметил

2023-08-30 10:57 UTC, zapaza requested changes

2023-08-30 10:57 UTC, zapaza commented on packages/client/src/components/ui/leaderboard-field/leaderboardField.tsx
>  				{isCurrentUser ? 'Ты' : userName}
лучше заменить на userName

2023-08-30 10:57 UTC, zapaza commented on packages/client/src/components/ui/leaderboard-field/leaderboardField.tsx
>  				{isCurrentUser ? 'Ты' : userName}
ты было просто написано для понятия, что это твоей лучшый результат

в итоге должно получиться что отображается username который выделен цветом

2023-08-30 10:57 UTC, zapaza commented on packages/client/src/core/game/gameHooks.ts
> +			ApiLeaderboard.updateScore(scoreData);
await не нужен?

2023-08-30 11:01 UTC, Sammily commented on packages/client/src/pages/leaderboard/leaderboardPage.tsx
> +				<h5 className="leaderboard__header text-xl-font-bold">Список Лидеров</h5>
да, по другой задаче доделываю локализацию

2023-08-31 08:00 UTC, zapaza approved these changes

2023-08-31 18:54 UTC, IvanPeleshok commented on packages/client/src/core/game/gameHooks.ts
> +		if (variables.player) {
Если запрос упадёт, то будет ли обработано исключение?

2023-08-31 18:54 UTC, IvanPeleshok commented on packages/client/src/core/game/gameHooks.ts
> +		if (variables.player) {
Предлагаю обернуть в try / catch

2023-08-31 18:55 UTC, IvanPeleshok commented on packages/client/src/store/leaderboard/leaderboard-slice.ts
> +		return (await ApiLeaderboard.getLeaders()) as LeaderboardDataType[];
Писать return await не очень популярная практика
Предлагаю разделять
```
const response = await request()
return response
```

2023-08-31 18:56 UTC, IvanPeleshok commented on packages/client/src/store/leaderboard/leaderboard-slice.ts
> +		return thunkAPI.rejectWithValue({
Круто, что есть обработка искоючения

2023-08-31 18:58 UTC, IvanPeleshok commented on packages/client/src/core/api/api-leaderboard.ts
> +		const response = await client.post('/leaderboard', data);
Для того, чтобы в дальнейшем не кастить типы, их можно передать в качестве дженерика в client.post<T>(...)

2023-09-01 20:05 UTC, IvanPeleshok commented on packages/client/src/pages/leaderboard/leaderboardPage.tsx
> +		fetchBoard();
Рекомендация: такие функции, которые будут вызваны один раз - лучше объявлять в useEffect, т.к при перерендере компоненты каждый раз будет создаваться функция fetchBoard, но если объявить внутри тела колбека useEffect с пустым массивом зависимостей, то функция будет создана один раз

2023-09-01 20:07 UTC, IvanPeleshok approved these changes
Проделана огромная работа!
Критических замечаний нет, хорошо потрудились)
Поздравляю, работа принята!

2023-09-02 06:50 UTC, merged