Feature/28 63
zapaza/teamwork_02 pull request #38
Opened 2023-08-31 22:23 UTC by SatanLittleHelper

**Ссылка на задачу в Linear:**

https://linear.app/28-mf-teamwork-02/issue/<28 63>

**Дополнительная информация:**
add 2 webAPI

2023-09-01 08:37 UTC, zapaza requested changes

2023-09-01 08:37 UTC, zapaza commented on packages/client/src/utils/gamepad.ts
> +};
по идее это можно записать в ENUM а не в сonst

ты тк ты тут ничего не перезаписываешь и это переменная всегда будет в памяти просто находиться

а enum удалиться после компиляции

это капля в море, но все же

2023-09-01 08:37 UTC, zapaza commented on packages/client/src/utils/gamepad.ts
> +	{ index: 9, event: 'Escape' },
`Escape` тоже бы добавить в keyboardEventsName, что бы не нарушать композицию

2023-09-01 08:37 UTC, zapaza commented on packages/client/src/utils/gamepad.ts
> +		window.addEventListener('gamepaddisconnected', this.dispatchGamePause);
я бы этот код проверил потом в ssr режиме

по идее этот этот метод вызывается в useEffetc, и все должно быть хорошо, но проверка не помешает

2023-09-01 08:37 UTC, zapaza commented on packages/client/src/utils/gamepad.ts
> +		this.interval = setInterval(this.pollGamepads, 100);
для setInterval и clearInterval, лучше использовать запись через window

`window.setInterval()`

2023-09-01 08:37 UTC, zapaza commented on packages/client/src/utils/gamepad.ts
> +		if (gamepads[0]) {
можно вынести в const

2023-09-01 08:37 UTC, zapaza commented on packages/client/src/utils/gamepad.ts
> +		if (gamepads[0]) {
дальше код будет читабельней

2023-09-01 08:37 UTC, zapaza commented on packages/client/src/utils/gamepad.ts
> +		if (gamepads[0]) {
и неплохо бы вывести предупреждение, на случай если подключено несколько геймпадов

2023-09-01 08:37 UTC, zapaza commented on packages/client/src/utils/gamepad.ts
> +		}
ну тут тоже normalizedStick[0] и normalizedStick[1] лучше наверно в константы вынести

ну или normalizedStick сделать не массивом, а объектом

2023-09-01 22:51 UTC, zapaza approved these changes

2023-09-02 15:59 UTC, Olegas commented on packages/client/src/utils/gamepad.ts
> +		this.interval = window.setInterval(this.pollGamepads, 100);
100 мс - не слишком медленно? Может имеет смысл на requestAnimationFrame делать?

2023-09-02 16:00 UTC, Olegas approved these changes
Gamepad API - круто! 
Работа принята.
Оставил еще один комментарий в качестве информации к размышлению

2023-09-06 07:31 UTC, merged