Add oauth
zapaza/teamwork_02 pull request #42
Opened 2023-09-06 10:48 UTC by Kustov-Ilya

Ссылка на задачу в Linear:

https://linear.app/28-mf-teamwork-02/issue/28-61

Дополнительная информация:

добавлена авторизация OAuth Yandex

2023-09-06 11:05 UTC, zapaza requested changes

2023-09-06 11:05 UTC, zapaza commented on packages/client/src/components/ui/oauth/oauth.tsx
> +}
вынеси это в функцию и возвращай ее

использовать в return условия, не очень читабельно, темболее такие
я с 3го раза увидел что тут условие

2023-09-06 11:05 UTC, zapaza commented
в названии пр пропустил букву `e`)

2023-09-06 13:56 UTC, Kustov-Ilya commented on packages/client/src/components/ui/oauth/oauth.tsx
> +}
done

2023-09-06 13:56 UTC, Kustov-Ilya commented on packages/client/src/core/api/api-oauth.ts
> +export default apiOAuth;
done

2023-09-06 13:56 UTC, Kustov-Ilya commented on packages/client/src/components/ui/oauth/oauth.tsx
> +export default function OAuth() {
done

2023-09-06 16:00 UTC, Sammily approved these changes

2023-09-07 06:51 UTC, Kustov-Ilya commented on packages/client/src/hooks/use-auth.tsx
> +				const urlParams = new URLSearchParams(location.search);
done, change to useSearchParams

2023-09-07 08:06 UTC, zapaza approved these changes

2023-09-07 19:26 UTC, Olegas approved these changes
Отлично! Работа принята.

2023-09-08 08:22 UTC, merged