feat: add-store-ssr
zapaza/teamwork_02 pull request #46
Opened 2023-09-10 07:34 UTC by TolkachevPeter

**Ссылка на задачу в Linear:** 
https://linear.app/28-mf-teamwork-02/issue/28-60/nastroit-redux-i-router-v-ssr

https://linear.app/28-mf-teamwork-02/issue/<TASK_NUMBER>

**Дополнительная информация:**

2023-09-10 07:36 UTC, TolkachevPeter commented on packages/client/src/store/index.ts
> +const store = setupStore();
вот тут боюсь, что дважды создается экземпляр store, но вроде работает, от этого избавиться не могу, поскольку store импортируется в других компонентах с игрой без useDispatch.

2023-09-10 07:38 UTC, TolkachevPeter commented on packages/server/index.ts
> +				.replace('<!--preloadedState-->', stateMarkup);
видимо так

2023-09-10 10:31 UTC, zapaza requested changes

2023-09-10 10:31 UTC, zapaza commented on packages/server/index.ts
> +				setupStore = (await vite!.ssrLoadModule(pathFileStore)).setupStore;
по идее ты можешь это перенести в условие на 54 строке

2023-09-11 08:05 UTC, TolkachevPeter commented on packages/server/index.ts
> +				setupStore = (await vite!.ssrLoadModule(pathFileStore)).setupStore;
это невозможно, нам тут по коду надо использовать переменную initialStateRender

2023-09-11 08:10 UTC, zapaza requested changes

2023-09-11 08:10 UTC, zapaza commented on packages/server/index.ts
> +				setupStore = (await vite!.ssrLoadModule(pathFileStore)).setupStore;
```
const [initialStateRender, appHtml] = await render();

if (!isDev) {
  render = (await import(ssrClientPath)).render;

  initialState = initialStateRender;
} else {
  render = (await vite!.ssrLoadModule(path.resolve(srcPath, 'ssr.tsx'))).render;

  setupStore = (await vite!.ssrLoadModule(pathFileStore)).setupStore;
  const store = setupStore();
  initialState = store.getState();
}
```

так она не буедт использоваться?

2023-09-11 08:23 UTC, TolkachevPeter commented on packages/server/index.ts
> +				setupStore = (await vite!.ssrLoadModule(pathFileStore)).setupStore;
ты хочешь сначала вызвать render, а потом его определить?

2023-09-11 08:26 UTC, zapaza commented on packages/server/index.ts
> +				setupStore = (await vite!.ssrLoadModule(pathFileStore)).setupStore;
а сори, я проглядел это

2023-09-11 17:57 UTC, zapaza approved these changes

2023-09-12 17:27 UTC, Olegas requested changes
Добрый день.
Есть вопросы по коду. Написал комментариями.
Прошу объяснить в комментариях.

2023-09-12 17:27 UTC, Olegas commented on packages/server/index.ts
> +			if (isDev) {
А для чего нужно это условие? Какая проблема тут решается? Выглядит странно

2023-09-12 17:27 UTC, Olegas commented on packages/client/src/store/index.ts
> +const store = setupStore();
А что за места приложения, которые работают со store напрямую без useDispatch?

2023-09-14 04:33 UTC, TolkachevPeter commented on packages/client/src/store/index.ts
> +const store = setupStore();
места, где не используется реакт, но написана логика самой игры.

Это не касается именно моей задачи, так сделал другой разработчик.

2023-09-14 04:35 UTC, TolkachevPeter commented on packages/server/index.ts
> +			if (isDev) {
согласен, удалил, store инициализируется в packages/client/ssr.tsx

2023-09-14 05:30 UTC, Olegas commented on packages/client/src/store/index.ts
> +const store = setupStore();
Тут, возможно, кроется простор для ошибок. Если где-то на сервере вы используете это глобальное состояние, то вы автоматически начнете делить его со всеми клиентами вашего приложения.
Если есть какие-то части приложения, которые не связаны с жизненным циклом React, я бы лучше выставил оттуда какие-то события, и уже по этим событиям внутри react-компонентов делал dispatch.
Redux как хранилище состояния - всего лишь деталь реализации вашего проекта. Базовые вещи не должны от него зависеть.
Это как совет, не влияет не приемку задачи.

2023-09-14 15:50 UTC, TolkachevPeter commented on packages/client/src/store/index.ts
> +const store = setupStore();
Согласен, но не знаю как поместить часть логики игры в реакт компоненты, чтобы вызывать от туда dispatch, уже пытался это сделать.

Что еще можно сделать для принятия данной задачи? Дедлайн уже через 3 дня, у меня еще задача висит по бэку с api))

2023-09-14 15:54 UTC, Olegas commented on packages/client/src/store/index.ts
> +const store = setupStore();
> Что еще можно сделать для принятия данной задачи? Дедлайн уже через 3 дня, у меня еще задача висит по бэку с api))

Для начала нужно ее на ревью обратно отправить )) У меня сейчас она висит в статусе "На стороне студента"

2023-09-14 16:49 UTC, TolkachevPeter commented on packages/client/src/store/index.ts
> +const store = setupStore();
Отправил, что-то письмо на почту не приходило с ревью.

2023-09-14 16:50 UTC, TolkachevPeter commented on packages/client/src/store/index.ts
> +const store = setupStore();
Спасибо)

2023-09-15 04:37 UTC, Olegas approved these changes
Работа принята

2023-09-15 05:35 UTC, merged