Feature/28 74 add forum API to forum-topic page
zapaza/teamwork_02 pull request #49
Opened 2023-09-14 21:19 UTC by SatanLittleHelper

**Ссылка на задачу в Linear:**

https://linear.app/28-mf-teamwork-02/issue/28-74

**Дополнительная информация:**

2023-09-15 19:28 UTC, Sammily commented on packages/client/src/core/api/api-forum.ts
> +		const response = await client.get('/topic', { offset, limit }, { withCredentials: false });
У меня без { withCredentials: false } работает, может в mockoon что-то ещё нужно настроить?

2023-09-15 20:29 UTC, Sammily approved these changes

2023-09-15 20:35 UTC, SatanLittleHelper commented on packages/client/src/core/api/api-forum.ts
> +		const response = await client.get('/topic', { offset, limit }, { withCredentials: false });
У меня не работает без, это в любом случае поправим, когда будет реальный бек

2023-09-16 10:38 UTC, Olegas requested changes
Добрый день.
Есть замечания по коду, нужно доработать.
Написал комментарии

2023-09-16 10:38 UTC, Olegas commented on packages/client/src/core/api/api-forum.ts
> +	schema: schemaType;
А зачем такой сложный тип для автора? Зачем нужно промежуточное поле schema? Почему нельзя сразу id + name?

2023-09-16 10:38 UTC, Olegas commented on packages/client/src/pages/forum-topic/forumTopicPage.tsx
> +	const topicId = Number(useLocation()?.search.match(/\d+/)?.[0]);
Есть API - URLSearchParams: https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams

2023-09-16 10:38 UTC, Olegas commented on packages/client/src/pages/forum-topic/forumTopicPage.tsx
> +		};
А для чего нужно делать async + await если результат никак не обрабатывается? Тут достаточно просто dispatch(fetchAllComments({ id: topicId })); непосредственно в эффекте

2023-09-16 10:38 UTC, Olegas commented on packages/client/src/pages/forum-topic/forumTopicPage.tsx
> +			id: forum.data.comments.length + 1,
Не надо так. Идентификаторы должен генерировать backend, клиент не должен их никак создавать, особенно на основании длины какой-то коллекции.

2023-09-16 10:38 UTC, Olegas commented on packages/client/src/store/forum/forumSlice.ts
> +import { createSlice } from '@reduxjs/toolkit';
В этом файле что-то не то с отступами. В предыдущем коде отступ 4 а тут больше

2023-09-16 10:38 UTC, Olegas commented on packages/client/src/store/forum/forumSlice.ts
> +				console.error('fetch topics failed');
А тут не надо что-то выставить? Или признак что данные загружены или сами данные заполнить чем-то пустым?

2023-09-16 10:38 UTC, Olegas commented on packages/client/src/store/forum/forumThunk.ts
> +);
Тоже что-то не то с отступами, не соответствует остальному коду

2023-09-16 10:38 UTC, Olegas commented on packages/client/src/store/forum/forumThunk.ts
> +	async (data: Record<string, any>, thunkAPI) => {
Здесь бы нужен тип нормальный. Тут же известно точно, какие поля должны быть и каких они типов.

2023-09-19 21:02 UTC, SatanLittleHelper commented on packages/client/src/core/api/api-forum.ts
> +	schema: schemaType;
Не получилось до конца разобраться со сваггером, от мокового бекенда из за этого вот так криво прилетало. Как будет реальный бек, тогда это переделается.

2023-09-19 21:35 UTC, SatanLittleHelper commented on packages/client/src/store/forum/forumSlice.ts
> +import { createSlice } from '@reduxjs/toolkit';
Да вроде все ок с отступами

2023-09-19 21:48 UTC, SatanLittleHelper commented on packages/client/src/store/forum/forumThunk.ts
> +);
Это что-то странное, в ide у меня весь код выглядит нормально, с отступами проблем нет. А тут действительно выглядит как то стремно

2023-09-20 17:12 UTC, Olegas commented on packages/client/src/store/forum/forumThunk.ts
> +);
Видимо в одних файлах пробелы, а в других табы

2023-09-20 17:12 UTC, Olegas commented on packages/client/src/pages/forum-topic/forumTopicPage.tsx
> +		fetchComments();
Если убрали async, то и отдельная функция не нужна

2023-09-20 17:13 UTC, Olegas commented on packages/client/src/pages/forum/forumPage.tsx
> +		fetchTopics();
Тут та же история что в файле ранее. Ненужный await

2023-09-20 17:13 UTC, Olegas approved these changes
Работа принята

2023-09-20 17:13 UTC, SatanLittleHelper commented on packages/client/src/store/forum/forumThunk.ts
> +);
Я притером прогнал оба файла, ничего не изменилось

2023-09-20 17:15 UTC, SatanLittleHelper commented on packages/client/src/pages/forum-topic/forumTopicPage.tsx
> +		fetchComments();
Посмотрю, спасибо.

2023-10-01 20:04 UTC, closed without merging